vienna_wfs:
  # Basis-Konfiguration
  url: "https://data.wien.gv.at/daten/geo"
  version: "1.1.0"
  request: "GetFeature"
  srsName: "EPSG:31256"
  outputFormat: "json"
  maxFeatures: 1000
  timeout: 30
  retries: 3

  # WFS Streams
  streams:
    - name: "Gebäudeinfo"
      layer: "ogdwien:GEBAEUDEINFOOGD"
      fields:
        - "OBJECTID"
        - "geometry"
        - "SE_ANNO_CAD_DATA"
      mapping:
        building_id: "OBJECTID"
        geometry: "geometry"
        cad_data: "SE_ANNO_CAD_DATA"

    - name: "Energieraumplan"
      layer: "ogdwien:ENERGIERAUMPLANOGD"
      fields:
        - "OBJECTID"
        - "geometry"
        - "ERPLABEL"
      mapping:
        energy_id: "OBJECTID"
        geometry: "geometry"
        energy_label: "ERPLABEL"

    - name: "Solarpotential"
      layer: "ogdwien:PVPOTENZIALEOGD"
      fields:
        - "OBJECTID"
        - "geometry"
        - "EIGNUNGSKLASSE"
      mapping:
        solar_id: "OBJECTID"
        geometry: "geometry"
        suitability: "EIGNUNGSKLASSE"

  # Merge-Felder für die Zusammenführung der Daten
  merge_fields:
    buildings:
      - building_id
      - geometry
      - cad_data
    energy:
      - energy_id
      - geometry
      - energy_label
    solar_potential:
      - solar_id
      - geometry
      - suitability

  # Layer-Definitionen
  layers:
    buildings:
      name: "GEBAEUDE_1_0_0"
      attributes:
        - OBJECTID
        - BAUJAHR
        - L_NUTZUNG
        - L_BAUTYP
        - GESCH_ANZ
        - BASIS_INV
        - L_BAUJ
    
    energy:
      name: "ogdwien:ENERGIERAUMPLANOGD"
      attributes:
        - OBJECTID
        - BEARB_DATUM
        - BEZNR
        - ERPLABEL
        - FL_ERP
        - GEBID
    
    solar_potential:
      name: "ogdwien:PVPOTENZIALEOGD"
      attributes:
        - OBJECTID
        - EIGNUNGSKLASSE
    
    green_spaces:
      name: "ogdwien:GRUENFREIFLOGD"
      attributes:
        - OBJECTID
        - LANDSCHAFT
        - FLAECHE
    
    land_use:
      name: "ogdwien:GENFLWIDMUNGOGD"
      attributes:
        - OBJECTID
        - WIDMUNGSKLASSE
        - WIDMUNGSKLASSE_TXT
        - WIDMUNG
        - WIDMUNG_TXT
        - FLAECHE
    
    noise_protection:
      name: "ogdwien:LAERMSCHUTZOGD"
      attributes:
        - OBJECTID
        - BESCHREIBUNG
        - LAENGE
        - FLAECHE
        - HMIN
        - HMAX

    typology:
      name: "ogdwien:GEBAEUDETYPOGD"
      attributes:
        - OBJECTID
        - BEZUG
        - OBJ_STR
        - OBJ_STR_TXT
        - OBJ_STR2
        - OBJ_STR2_TXT
        - BAUTYP
        - BAUTYP_TXT
        - ASC
        - SE_ANNO_CAD_DATA

    building_model:
      name: "ogdwien:FMZKBKMOGD"
      attributes:
        - OBJECTID
        - BEZUG
        - OBJ_STR
        - OBJ_STR_TXT
        - OBJ_STR2
        - OBJ_STR2_TXT
        - BAUTYP
        - BAUTYP_TXT
        - ASC
        - SE_ANNO_CAD_DATA
        - FLAECHE
        - VOLUMEN
        - GESCH_ANZ
        - BAUJAHR

    land_use_2022:
      name: "ogdwien:REALNUT2022OGD"
      attributes:
        - OBJECTID
        - BEZ
        - ZBEZ
        - ZGEB
        - BLK
        - NUTZUNG_CODE
        - NUTZUNG_LEVEL1
        - NUTZUNG_LEVEL2
        - NUTZUNG_LEVEL3
        - FLAECHE
        - SE_ANNO_CAD_DATA

  # Feld-Mapping für die Normalisierung
  field_mapping:
    buildings:
      OBJECTID: "building_id"
      BAUJAHR: "construction_year"
      L_NUTZUNG: "usage"
      L_BAUTYP: "type"
      GESCH_ANZ: "floors"
      BASIS_INV: "foundation_type"
      L_BAUJ: "construction_year"
    
    energy:
      OBJECTID: "energy_id"
      BEARB_DATUM: "measurement_date"
      BEZNR: "energy_class"
      ERPLABEL: "energy_label"
      FL_ERP: "energy_performance"
      GEBID: "energy_id"
    
    solar_potential:
      OBJECTID: "solar_id"
      EIGNUNGSKLASSE: "potential_class"
    
    green_spaces:
      OBJECTID: "green_id"
      LANDSCHAFT: "type"
      FLAECHE: "area"
    
    land_use:
      OBJECTID: "landuse_id"
      WIDMUNGSKLASSE: "designation_class"
      WIDMUNGSKLASSE_TXT: "designation_class_text"
      WIDMUNG: "designation"
      WIDMUNG_TXT: "designation_text"
      FLAECHE: "area"
    
    noise_protection:
      OBJECTID: "noise_id"
      BESCHREIBUNG: "description"
      LAENGE: "length"
      FLAECHE: "area"
      HMIN: "min_height"
      HMAX: "max_height"

    typology:
      OBJECTID: "typology_id"
      BEZUG: "reference"
      OBJ_STR: "structure"
      OBJ_STR_TXT: "structure_text"
      OBJ_STR2: "structure2"
      OBJ_STR2_TXT: "structure2_text"
      BAUTYP: "building_type"
      BAUTYP_TXT: "building_type_text"
      ASC: "asc"
      SE_ANNO_CAD_DATA: "cad_data"

    building_model:
      OBJECTID: "model_id"
      BEZUG: "reference"
      OBJ_STR: "structure"
      OBJ_STR_TXT: "structure_text"
      OBJ_STR2: "structure2"
      OBJ_STR2_TXT: "structure2_text"
      BAUTYP: "building_type"
      BAUTYP_TXT: "building_type_text"
      ASC: "asc"
      SE_ANNO_CAD_DATA: "cad_data"
      FLAECHE: "area"
      VOLUMEN: "volume"
      GESCH_ANZ: "floors"
      BAUJAHR: "construction_year"

  # Bauperioden-Mapping
  periods:
    "1848 - 1918": 
      categories: ["_A", "_B"]
    "1919 - 1945": 
      categories: ["_C"]
    "nach 1945":
      categories: ["_D", "_E", "_F", "_G", "_H", "_I", "_J", "_K", "_L"]

  # Gebäudetypen-Mapping
  building_types:
    "10.-Kaufhäuser": "AB"
    "11.-Einkaufszentren": "AB"
    "12.-Gewerbebetriebe": "AB"
    "13.-Industriebauten": "AB"
    "14.-Bauten des öffentlichen und privaten Verkehrs": "TH"
    "15.-Bauten der öffentlichen und privaten Wohlfahrt": "TH"
    "W1.1.-bäuerl.dom.Baustrukt.-Streck- u. Hakenhof": "SFH"
    "W1.2.-bäuerl.dom.Baustrukt.-Zwerchh.u.Gassenfrontenhaus": "SFH"
    "W2.1.-Bürgerhaus-kleine Haustypen ohne Hof": "MFH"
    "W2.2.-Bürgerhaus-Haus auf tiefer,schmaler Parzelle,ohne Hof": "MFH"
    "W3.1.-Mieth.s.d.Gründerzeit-Straßentrakter": "AB"
    "W3.2.-Mieth.s.d.Gründerzeit-Seitenflügelhaus": "AB"
    "W3.3.-Mieth.s.d.Gründerzeit-Doppeltrakter mit Verbindungstr.": "AB"
    "W4.1.-soz.u.gemeinn.Wohnb.-Baulückenbebauungen": "MFH"
    "W4.2.-soz.u.gemeinn.Wohnb.-Hofbebauungen/Superblocks": "AB"
    "W4.3.-soz.u.gemeinn.Wohnb.-Siedlungen in Zeilenbauweise": "MFH"
    "W4.4.-soz.u.gemeinn.Wohnb.-Siedlungen,1-,2-u.Mehrfamilienh.": "SFH"
    "W5.1.-freist.1-,2-u.Mehrfamilienh.-Villen in Randbebauung": "SFH"
    "W5.2.-freist.1-,2-u.Mehrfamilienh.-freistehende Villen": "SFH"
    "W6.1.-Sonderwohnbauten-Hotel und Pension": "HR"
    "W6.2.-Sonderwohnbauten-Heim,Pflegeanstalt,Spitalsbauten": "TH"

  # Räumliche Operationen
  spatial_operations:
    inherit: "../common_config.yml:common.spatial" 