vienna_wfs:
  # Basis-Konfiguration
  url: "https://data.wien.gv.at/daten/geo"
  version: "1.1.0"
  request: "GetFeature"
  srsName: "EPSG:31256"
  outputFormat: "json"
  maxFeatures: 1000
  timeout: 30
  retries: 3

  # WFS Streams
  streams:
    - name: "Gebäudeinfo"
      layer: "ogdwien:GEBAEUDEINFOOGD"
      priority: 1
      fields:
        - "OBJECTID"
        - "geometry"
        - "BAUJAHR"
        - "L_NUTZUNG"
        - "L_BAUTYP"
        - "GESCH_ANZ"
        - "BASIS_INV"
        - "L_BAUJ"
        - "ORIG_PARZ"
        - "ORIG_FASS"
        - "ORIG_KERN"
        - "ORIG_FENSTER"
        - "ORIG_DACH"
      mapping:
        building_id: "OBJECTID"
        geometry: "geometry"
        construction_year: "BAUJAHR"
        usage: "L_NUTZUNG"
        building_type: "L_BAUTYP"
        floors: "GESCH_ANZ"
        foundation_type: "BASIS_INV"
        construction_period: "L_BAUJ"
        original_parcel: "ORIG_PARZ"
        original_facade: "ORIG_FASS"
        original_core: "ORIG_KERN"
        original_windows: "ORIG_FENSTER"
        original_roof: "ORIG_DACH"

    - name: "Energieraumplan"
      layer: "ogdwien:ENERGIERAUMPLANOGD"
      priority: 2
      fields:
        - "OBJECTID"
        - "geometry"
        - "ERPLABEL"
        - "BEARB_DATUM"
        - "BEZNR"
        - "FL_ERP"
      mapping:
        energy_id: "OBJECTID"
        geometry: "geometry"
        energy_label: "ERPLABEL"
        measurement_date: "BEARB_DATUM"
        energy_class: "BEZNR"
        energy_performance: "FL_ERP"

    - name: "Solarpotential"
      layer: "ogdwien:PVPOTENZIALEOGD"
      priority: 3
      fields:
        - "OBJECTID"
        - "geometry"
        - "EIGNUNGSKLASSE"
      mapping:
        solar_id: "OBJECTID"
        geometry: "geometry"
        suitability: "EIGNUNGSKLASSE"

    - name: "Grünflächen"
      layer: "ogdwien:GRUENFREIFLOGD"
      fields:
        - "OBJECTID"
        - "geometry"
        - "LANDSCHAFT"
        - "FLAECHE"
      mapping:
        green_id: "OBJECTID"
        geometry: "geometry"
        type: "LANDSCHAFT"
        area: "FLAECHE"

    - name: "Flächenwidmung"
      layer: "ogdwien:GENFLWIDMUNGOGD"
      priority: 5
      fields:
        - "OBJECTID"
        - "WIDMUNGSKLASSE"
        - "WIDMUNGSKLASSE_TXT"
        - "BEZIRK"
        - "UMFANG"
        - "FLAECHE"
        - "WIDMUNG"
        - "WIDMUNG_TXT"
      mapping:
        landuse_id: "OBJECTID"
        designation_class: "WIDMUNGSKLASSE"
        designation_class_text: "WIDMUNGSKLASSE_TXT"
        designation: "WIDMUNG"
        designation_text: "WIDMUNG_TXT"


    - name: "Gebäudetypologie"
      layer: "ogdwien:GEBAEUDETYPOGD"
      priority: 4
      fields:
        - "OBJECTID"
        - "BEZUG"
        - "OBJ_STR"
        - "OBJ_STR_TXT"
        - "OBJ_STR2"
        - "OBJ_STR2_TXT"
        - "BAUTYP"
        - "BAUTYP_TXT"
        - "ACD"
      mapping:
        typology_id: "OBJECTID"
        structure: "OBJ_STR"
        structure_text: "OBJ_STR_TXT"
        structure2: "OBJ_STR2"
        structure2_text: "OBJ_STR2_TXT"

    - name: "Gebäudemodell"
      layer: "ogdwien:FMZKBKMOGD"
      priority: 5
      fields:
        - "FMZK_ID"
        - "F_KLASSE"
        - "LAYER"
        - "BEZUG"
        - "H_KLASSE"
        - "KLASSE_SUB"
        - "O_KOTE"
        - "U_KOTE"
        - "T_KOTE"
        - "BW_GEB_ID"
        - "BW_BRK_ID"
        - "BW_SON_ID"
        - "SE_SDO_ROWID"
      mapping:
        model_id: "OBJECTID"
        upper_elevation: "O_KOTE"
        lower_elevation: "U_KOTE"
        terrain_elevation: "T_KOTE"

    - name: "Realnutzung"
      layer: "ogdwien:REALNUT2022OGD"
      priority: 6
      fields:
        - "OBJECTID"
        - "BEZ"
        - "ZBEZ"
        - "ZGEB"
        - "BLK"
        - "NUTZUNG_CODE"
        - "NUTZUNG_LEVEL1"
        - "NUTZUNG_LEVEL2"
        - "NUTZUNG_LEVEL3"
        - "FLAECHE"
      mapping:
        landuse_id: "OBJECTID"
        usage_code: "NUTZUNG_CODE"
        usage_level1: "NUTZUNG_LEVEL1"
        usage_level2: "NUTZUNG_LEVEL2"
        usage_level3: "NUTZUNG_LEVEL3"
        area: "FLAECHE"

  # Merge-Felder für die Zusammenführung der Daten
  merge_fields:
    buildings:
      - building_id
      - geometry
      - cad_data
      - construction_year
      - usage
      - building_type
      - floors
      - foundation_type
      - construction_period
    energy:
      - energy_id
      - geometry
      - energy_label
      - measurement_date
      - energy_class
      - energy_performance
      - building_id
    solar_potential:
      - solar_id
      - geometry
      - suitability

  # Bauperioden-Mapping
  periods:
    "1848 - 1918": 
      categories: ["_A", "_B"]
    "1919 - 1945": 
      categories: ["_C"]
    "nach 1945":
      categories: ["_D", "_E", "_F", "_G", "_H", "_I", "_J", "_K", "_L"]

  # Gebäudetypen-Mapping
  building_types:
    "10.-Kaufhäuser": "AB"
    "11.-Einkaufszentren": "AB"
    "12.-Gewerbebetriebe": "AB"
    "13.-Industriebauten": "AB"
    "14.-Bauten des öffentlichen und privaten Verkehrs": "TH"
    "15.-Bauten der öffentlichen und privaten Wohlfahrt": "TH"
    "W1.1.-bäuerl.dom.Baustrukt.-Streck- u. Hakenhof": "SFH"
    "W1.2.-bäuerl.dom.Baustrukt.-Zwerchh.u.Gassenfrontenhaus": "SFH"
    "W2.1.-Bürgerhaus-kleine Haustypen ohne Hof": "MFH"
    "W2.2.-Bürgerhaus-Haus auf tiefer,schmaler Parzelle,ohne Hof": "MFH"
    "W3.1.-Mieth.s.d.Gründerzeit-Straßentrakter": "AB"
    "W3.2.-Mieth.s.d.Gründerzeit-Seitenflügelhaus": "AB"
    "W3.3.-Mieth.s.d.Gründerzeit-Doppeltrakter mit Verbindungstr.": "AB"
    "W4.1.-soz.u.gemeinn.Wohnb.-Baulückenbebauungen": "MFH"
    "W4.2.-soz.u.gemeinn.Wohnb.-Hofbebauungen/Superblocks": "AB"
    "W4.3.-soz.u.gemeinn.Wohnb.-Siedlungen in Zeilenbauweise": "MFH"
    "W4.4.-soz.u.gemeinn.Wohnb.-Siedlungen,1-,2-u.Mehrfamilienh.": "SFH"
    "W5.1.-freist.1-,2-u.Mehrfamilienh.-Villen in Randbebauung": "SFH"
    "W5.2.-freist.1-,2-u.Mehrfamilienh.-freistehende Villen": "SFH"
    "W6.1.-Sonderwohnbauten-Hotel und Pension": "HR"
    "W6.2.-Sonderwohnbauten-Heim,Pflegeanstalt,Spitalsbauten": "TH"

  # Räumliche Operationen
  spatial_operations:
    inherit: "../common_config.yml:common.spatial" 