osm:
  # API-Einstellungen
  overpass_endpoint: "https://overpass-api.de/api/interpreter"
  timeout: 300
  retries: 3

  # Gebäude-Standardwerte
  building_defaults:
    height: 10  # Standardhöhe in Metern
    floors: 3   # Standardanzahl der Stockwerke
    year: 1990  # Standardbaujahr
  
  # Umgebungsgebäude-Einstellungen
  surroundings:
    buffer_distance: 100  # Meter
    building_types:
      - residential
      - commercial
      - industrial
      - school
      - university
      - hospital
    
  # Straßen-Einstellungen
  streets:
    buffer_distance: 100  # Meter
    street_types:
      primary: true
      secondary: true
      tertiary: true
      residential: true
      service: true
      living_street: true
      pedestrian: true
      footway: true
      cycleway: true
    
  # Gebäudetyp-Mapping
  building_type_mapping:
    residential: "MFH"
    apartments: "MFH"
    house: "SFH"
    commercial: "OFFICE"
    retail: "RETAIL"
    school: "SCHOOL"
    university: "UNIVERSITY"
    hospital: "HOSPITAL"
    industrial: "INDUSTRIAL"
    default: "OTHER"

  # Tags für verschiedene Objekttypen
  tags:
    buildings:
      - "building"
    infrastructure:
      - "highway"
      - "railway"
    natural:
      - "natural"
      - "landuse" 