from setuptools import setup, find_packages

setup(
    name="sgh-master",
    version="0.1.0",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "geopandas",
        "pandas",
        "numpy",
        "shapely",
        "pyyaml",
        "requests",
        "overpy",
        "lxml",
        "pyproj",
        "pyogrio",
        "osmnx",
        "owslib",
        "py3dtiles",
        "supabase",
        "python-dotenv",
        "openpyxl",
        "simpledbf",
        "dbf",
        "pyshp",
        "ifcopenshell",
        "isodate",
        "networkx",
        "click"
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-cov",
            "black",
            "flake8",
            "mypy"
        ]
    }
) 