vienna:
  # Basis-Konfiguration
  crs: "EPSG:31256"  # Wien GK East
  city_name: "Wien"
  district: "1. Bezirk"
  
  # WFS-Konfiguration
  vienna_wfs:
    url: "https://data.wien.gv.at/daten/OGDEXT/wfs/1.0.0/WFS_OGDEXT_GEBAEUDE_1_0_0"
    layer: "GEBAEUDE_1_0_0"
    version: "1.0.0"
    request: "GetFeature"
    typeNames: "GEBAEUDE_1_0_0"
    outputFormat: "json"
    srsName: "EPSG:31256"
    maxFeatures: 1000
  
  # Gebäudestandards für Wien
  building_standards:
    default_height: 12
    default_floor_height: 3
    default_floors_ag: 4
    default_floors_bg: 1
    default_year: 1970
    
  # Bauperioden für Wien
  construction_periods:
    "1848 - 1918": 
      categories: ["_A", "_B"]
      description: "Gründerzeit"
    "1919 - 1945": 
      categories: ["_C"]
      description: "Zwischenkriegszeit"
    "1946 - 1957":
      categories: ["_D"]
      description: "Nachkriegszeit"
    "1958 - 1968":
      categories: ["_E"]
      description: "Wirtschaftswunder"
    "1969 - 1978":
      categories: ["_F"]
      description: "Moderne"
    "1979 - 1983":
      categories: ["_G"]
      description: "Ölkrise"
    "1984 - 1994":
      categories: ["_H"]
      description: "Postmoderne"
    "1995 - 2001":
      categories: ["_I"]
      description: "Neue Architektur"
    "2002 - 2009":
      categories: ["_J"]
      description: "Nachhaltigkeit"
    "2010 - 2015":
      categories: ["_K"]
      description: "Smart City"
    "2016 - heute":
      categories: ["_L"]
      description: "Zukunft"
      
  # Gebäudetypen für Wien
  building_types:
    residential:
      - "MFH"
      - "SFH"
      - "AB"
    commercial:
      - "OFFICE"
      - "RETAIL"
      - "INDUSTRIAL"
    special:
      - "HOSPITAL"
      - "SCHOOL"
      - "HOTEL"
      
  # Standardwerte für den 1. Bezirk
  district_defaults:
    building_height: 15
    floor_height: 3.5
    floors_ag: 5
    floors_bg: 1
    construction_year: 1900
    building_type: "AB"
    building_use: "MULTI_RES"
    
  # Datenpfade
  data_paths:
    citygml: "data/citygml/vienna_1st_district.gml"
    output: "data/output" 