# CityGML Verarbeitungskonfiguration

input:
  directory: "data/citygml"
  file_pattern: "*.gml"
  encoding: "utf-8"

processing:
  crs:
    input: "EPSG:31256"  # Standard-CRS für Berlin
    output: "EPSG:4326"  # WGS84
  lod_level: 2
  validation:
    check_geometry: true
    fix_invalid: true
  attributes:
    required:
      - building_id
      - storeys
      - measured_height
      - year_of_construction
      - building_type
      - roof_type

citygml_fields:
  building_id:
    xpath: '@gml:id'
    type: str
  storeys:
    xpath: './/bldg:storeysAboveGround'
    type: int
  measured_height:
    xpath: './/gen:doubleAttribute[gen:name="Gebäudehöhe"]/gen:value'
    type: float
  year_of_construction:
    xpath: './/gen:stringAttribute[gen:name="Baujahr"]/gen:value'
    type: str
  building_type:
    xpath: './/gen:stringAttribute[gen:name="Nutzung"]/gen:value'
    type: str
  roof_type:
    xpath: './/gen:stringAttribute[gen:name="Dachform"]/gen:value'
    type: str



output:
  formats:
    - type: "3dtiles"
      directory: "data/processed/citygml/3dtiles"
      options:
        geometric_error: 10.0
        refinement: "REPLACE"
    - type: "geojson"
      directory: "data/processed/citygml/geojson"
      options:
        simplify_tolerance: 0.1
        include_height: true

transformations:
  building_id:
    function: "shorten_id"
    max_length: 10
  height:
    function: "convert_units"
    from: "m"
    to: "m"
  storeys:
    function: "to_integer"

logging:
  level: "INFO"
  file: "logs/citygml_processing.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

cache:
  enabled: true
  directory: "cache/citygml"
  max_size_mb: 1000
  ttl_hours: 24
