streets:
  network_type: "all_private"
  include_types:
    - motorway
    - trunk
    - primary
    - secondary
    - tertiary
    - residential
    - unclassified
    - motorway_link
    - trunk_link
    - primary_link
    - secondary_link
    - tertiary_link
    - service
    - living_street
    - pedestrian
    - track
    - path
    - footway
    - cycleway
    - private 

osm:
  street_types:
    - 'motorway'
    - 'trunk'
    - 'primary'
    - 'secondary'
    - 'tertiary'
    - 'residential'
    - 'service'
  building_tags:
    - 'building'
    - 'building:levels'
    - 'building:height'
    - 'start_date'
  timeout: 30
  retries: 3
  
defaults:
  street_width:
    motorway: 12
    trunk: 10
    primary: 8
    secondary: 6
    tertiary: 5
    residential: 4
    service: 3 