streets:
  network_type: "all_private"
  include_types:
    - motorway
    - trunk
    - primary
    - secondary
    - tertiary
    - residential
    - unclassified
    - motorway_link
    - trunk_link
    - primary_link
    - secondary_link
    - tertiary_link
    - service
    - living_street
    - pedestrian
    - track
    - path
    - footway
    - cycleway
    - private 