paths:
  input:
    format: citygml
    files:
      citygml: "local/data/citygml/099082.gml"
      geojson: "local/data/geojson/buildings.geojson"
  scenario_folders:
    inputs:
      building-geometry: "inputs/building-geometry"
      building-properties: "inputs/building-properties"
      networks: "inputs/networks"
      technology: "inputs/technology"
    outputs:
      results: "outputs/results"
      plots: "outputs/plots"
  cea_inputs: "inputs"
  cea_outputs: "outputs"
  cea_temp: "temp"

cea_settings:
  scenario_path: ""
  weather_file: "weather.epw"
  reference_case: "reference-case"
  sensitivity_analysis: false
  optimization: false
  building:
    default_height: 20.0
    default_floors: 5
    default_occupancy: 0.8
    default_construction_year: 1990
    
  network:
    default_lane_width: 3.5
    default_speed_limit: 50
    default_capacity: 1000
    
  simulation:
    start_date: "2024-01-01"
    end_date: "2024-12-31"
    time_step: 3600  # 1 hour in seconds
    
  output:
    save_intermediate: true
    format: "geojson"
    crs: "EPSG:31256"

osm_defaults:
  building_height: 12
  floor_height: 3
  floors_ag: 4
  floors_bg: 1
  default_floors: 4
  building_type: "MFH"
  building_use: "MULTI_RES"
  construction_year: 1970
  protection_level: 0
  category: "MFH"
  REFERENCE: "OSM"
  building_type_mapping:
    residential: ["MFH", "MULTI_RES"]
    apartments: ["MFH", "MULTI_RES"]
    house: ["SFH", "SINGLE_RES"]
    commercial: ["OFFICE", "OFFICE"]
    retail: ["RETAIL", "RETAIL"] 