common:
  # Koordinatensystem
  crs: "EPSG:31256"  # Wien GK East
  
  # WFS Basis-Konfiguration
  wfs:
    url: "https://data.wien.gv.at/daten/geo"
    version: "1.1.0"
    timeout: 30
    retries: 3

  # Standardwerte für Gebäude
  building_defaults:
    height: 12
    floor_height: 3
    floors_ag: 4
    floors_bg: 1
    construction_year: 1970
    protection_level: 0
    building_type: "MFH"
    building_use: "MULTI_RES"

  # Logging-Konfiguration
  logging:
    file:
      level: DEBUG
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      encoding: 'utf-8'
    console:
      level: INFO
      format: '%(message)s'
    log_dir: 'logs'
    filename_pattern: '{process_name}_{timestamp}.log'

  # Räumliche Operationen
  spatial:
    buffer_distance: 50.0  # Meter
    intersection_tolerance: 0.1  # Meter
    site_buffer: 100  # Meter
    surrounding_buildings: 150  # Meter 