# CEA-Umgebungsvariablen
cea_env:
  cea_env_path: "F:/Users/ambi/Documents/CityEnergyAnalyst/dependencies/cea-env.bat"
  weather_base: "F:/Users/ambi/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/databases/weather"
  database_base: "F:/Users/ambi/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/database"

# Umgebungseinstellungen
geometry:
  site_buffer_distance: "../common_config.yml:common.spatial.site_buffer"
  surrounding_buildings_distance: "../common_config.yml:common.spatial.surrounding_buildings"
  osm_defaults:
    inherit: "../common_config.yml:common.building_defaults"

# Standardwerte für Gebäude
building_defaults:
  inherit: "../common_config.yml:common.building_defaults"

# Datenquellenwahl
data_source: "citygml"  # oder "geojson" abhängig vom verwendeten Datensat

# Projektinformationen
project:
  name: "Wien_Testgebiet"
  location: "Wien"
  description: "Testgebiet in Wien"
  scenario: "baseline"

# WFS-Konfiguration wird aus wfs_config.yml importiert
data_sources:
  wfs:
    inherit: "../wfs/wfs_config.yml:vienna_wfs"

# Logging-Konfiguration wird aus common_config.yml importiert
logging:
  inherit: "../common_config.yml:common.logging"

site_polygon:
  buffer_distance: "../common_config.yml:common.spatial.buffer_distance"
  simplify_tolerance: "../common_config.yml:common.spatial.intersection_tolerance"

surroundings:
  buffer_distance: "../common_config.yml:common.spatial.site_buffer"
  building_defaults:
    inherit: "../common_config.yml:common.building_defaults"

file_formats:
  shp_driver: "ESRI Shapefile"
  gml_encoding: "utf-8"

paths:
  inputs:
    citygml: "data/citygml"
    geojson: "data/geojson"
  outputs:
    geometry: "geometry"
    networks: "networks"
    properties: "building-properties"
    scenarios: "scenarios"

defaults:
  project_name: "CityGMLProject"
  scenario_name: "baseline"
  crs: "../common_config.yml:common.crs"
