osm:
  # Gemeinsame Einstellungen
  bbox: [16.3, 48.2, 16.4, 48.3]  # Wien
  filters: {}
  defaults: {}
  cache:
    enabled: true
    directory: "cache/osm"
  
  # Gebäude-spezifische Einstellungen
  buildings:
    tags:
      - building
      - amenity
    filters:
      building: true
    defaults:
      height: 10
      floors: 3
      year: 1990
      category: "residential"
      REFERENCE: ""
  
  # Straßen-spezifische Einstellungen
  streets:
    tags:
      - highway
    filters:
      highway: ["primary", "secondary", "tertiary", "residential"]
    defaults:
      width: 10
      lanes: 2
    street_types:
      primary: true
      secondary: true
      tertiary: true
      residential: true 