# Migrated from local/cfg/osm/osm_config.yml
osm:
  bbox:
    min_lat: 48.1
    min_lon: 16.3
    max_lat: 48.3
    max_lon: 16.5
  
  filters:
    buildings:
      tags:
        - key: "building"
          values: ["yes", "residential", "commercial", "industrial", "office"]
    
    streets:
      tags:
        - key: "highway"
          values: ["primary", "secondary", "tertiary", "residential"]
  
  defaults:
    building:
      height: 10
      floors: 3
      year: 1990
      type: "RESIDENTIAL"
    
    street:
      lanes: 2
      width: 6
  
  cache:
    enabled: true
    directory: "data/cache/osm"
    expiry: 86400  # 24 Stunden in Sekunden 