# CityGML Konfiguration
base_path: data/raw/citygml
default_file: 099082.gml

# Debug und Verarbeitungsoptionen
debug:
  enabled: true
  split_meta_fields: false

namespaces:
  bldg: http://www.opengis.net/citygml/building/1.0
  gml: http://www.opengis.net/gml
  gen: http://www.opengis.net/citygml/generics/1.0
  core: http://www.opengis.net/citygml/1.0
  xAL: urn:oasis:names:tc:ciq:xsdschema:xAL:2.0

# Alle möglichen Felder sammeln, Pflichtfelder später definieren
collect_all_fields: true
required_fields: []

geometry:
  srs_name: EPSG:31256
  min_area: 1.0
  validate: true
  validation:
    check_validity: true
    fix_invalid: true
    check_area: true
    min_area: 1.0
    remove_small: true

file_formats:
  - geojson
  - shp

output:
  geojson:
    directory: outputs/results
    options:
      driver: GeoJSON
      encoding: utf-8
      simplify_tolerance: 0.1

citygml_fields:
  # Basis-Attribute
  gml_id:
    xpath: "@{gml}id"
    type: str
  
  gml_name:
    xpath: ".//gml:name"
    type: str
    
  core_creationdate:
    xpath: ".//core:creationDate"
    type: str

  # Höhenattribute
  measured_height:
    xpath: ".//bldg:measuredHeight"
    type: float
    
  height:
    xpath: ".//gen:doubleAttribute[gen:name='Height']/gen:value"
    type: float
    
  roof_height:
    xpath: ".//gen:doubleAttribute[gen:name='HoeheDach']/gen:value"
    type: float
    
  ground_height:
    xpath: ".//gen:doubleAttribute[gen:name='HoeheGrund']/gen:value"
    type: float
    
  terrain_height:
    xpath: ".//gen:doubleAttribute[gen:name='TerrainHeight']/gen:value"
    type: float
    
  lowest_eaves:
    xpath: ".//gen:doubleAttribute[gen:name='NiedrigsteTraufeDesGebaeudes']/gen:value"
    type: float

  # Koordinaten
  latitude:
    xpath: ".//gen:doubleAttribute[gen:name='Latitude']/gen:value"
    type: float
    
  longitude:
    xpath: ".//gen:doubleAttribute[gen:name='Longitude']/gen:value"
    type: float

  # Gebäudeattribute
  roof_type:
    xpath: ".//bldg:roofType"
    type: str
    
  sheet_number:
    xpath: ".//gen:stringAttribute[gen:name='Blattnummer']/gen:value"
    type: str

  # Zusätzliche Attribute für spätere Verarbeitung
  storeys_above_ground:
    xpath: ".//bldg:storeysAboveGround"
    type: int
    
  building_function:
    xpath: ".//bldg:function"
    type: str
    
  building_usage:
    xpath: ".//bldg:usage"
    type: str

debug: true

# Statistik-Einstellungen
statistics:
  collect_empty_fields: true
  report_field_coverage: true
  min_coverage_threshold: 0.1  # 10% Mindestabdeckung für Felder

# Fallback-XPath für Adressfelder
fallback_address_xpath:
  street: "Building/address/Address/street"
  house_no: "Building/address/Address/houseNumber"
  postcode: "Building/address/Address/postalCode"
  city: "Building/address/Address/city"
  country: "Building/address/Address/country"

building_type_mapping:
  "1000": "AB"
  "2000": "NWG"
  "3000": "OFFICE"
  "4000": "RETAIL"
  "5000": "INDUSTRIAL"
  "6000": "HOSPITAL"
  "7000": "SCHOOL"
  "8000": "HOTEL"

cea_fields:
  Name:
    source: name
    type: str
  Year:
    source: year_of_construction
    type: int
  Use_Type:
    source: building_type
    type: str
  Height_AG:
    source: measured_height
    type: float
  Floors_AG:
    source: measured_height
    type: int
    transform: "max(1, int(x / 3.5))"  # Geschosshöhe ~3.5m
  Street:
    source: street
    type: str
  Streetnumber:
    source: house_no
    type: str
  Postcode:
    source: postcode
    type: str
  City:
    source: city
    type: str

attributes:
  required:
    - building_id
    - height
    - storeys
    - building_type
    - year_of_construction
  
  optional:
    - roof_type
    - ground_height
    - usage
    - address
  
  xpaths:
    building_id:
      xpath: ["@gml:id"]
      type: str
      
    height:
      xpath: 
        - "bldg:measuredHeight"
        - "bldg:height"
        - "gen:doubleAttribute[gen:name='Gebäudehöhe']/gen:value"
      type: float
      fallback: 10.0
      
    storeys:
      xpath:
        - "bldg:storeysAboveGround"
        - "bldg:numberOfFloorsAboveGround"
        - "gen:intAttribute[gen:name='AnzahlGeschosse']/gen:value"
      type: int
      fallback: 3
      
    building_type:
      xpath:
        - "bldg:function"
        - "bldg:usage"
        - "bldg:buildingType"
      type: str
      fallback: "RESIDENTIAL"
      
    year_of_construction:
      xpath:
        - "bldg:yearOfConstruction"
        - "gen:stringAttribute[gen:name='Baujahr']/gen:value"
        - "gen:intAttribute[gen:name='Baujahr']/gen:value"
      type: int
      search_text: ["Baujahr", "Errichtungsjahr", "Erbaut"]
      
    roof_type:
      xpath:
        - "bldg:roofType"
        - "bldg:roofForm"
      type: str
      
    ground_height:
      xpath:
        - "bldg:groundHeight"
        - "gen:doubleAttribute[gen:name='Grundhöhe']/gen:value"
      type: float
      fallback: 0.0
      
    usage:
      xpath:
        - "bldg:usage"
        - "gen:stringAttribute[gen:name='Nutzung']/gen:value"
      type: str
      search_text: ["Nutzung", "Verwendung"]
      
    address:
      xpath:
        - ".//bldg:address//xal:thoroughfare"
        - ".//bldg:address//xal:streetName"
      type: str 