# CityGML Konfiguration
base_path: data/raw/citygml
default_file: 099082.gml

# Debug und Verarbeitungsoptionen
debug: true  # Aktiviert detailliertes Logging
split_meta_fields: false  # Metadaten in separate Spalten aufsplitten

namespaces:
  bldg: http://www.opengis.net/citygml/building/1.0
  gml: http://www.opengis.net/gml
  gen: http://www.opengis.net/citygml/generics/1.0
  core: http://www.opengis.net/citygml/1.0
  xAL: urn:oasis:names:tc:ciq:xsdschema:xAL:2.0

required_fields:
  - measured_height
  - year_of_construction
  - building_type

geometry:
  srs_name: EPSG:31256
  min_area: 10.0
  validate: true
  validation:
    check_validity: true
    fix_invalid: true
    check_area: true
    min_area: 10.0
    remove_small: false

file_formats:
  - geojson
  - shp

output:
  geojson:
    directory: data/processed/geojson
    options:
      driver: GeoJSON
      encoding: utf-8
      simplify_tolerance: 0.1  # Optional: Geometrie-Vereinfachung
  shp:
    directory: data/processed/shp
    options:
      driver: ESRI Shapefile
      encoding: utf-8

citygml_fields:
  measured_height:
    xpath: .//bldg:measuredHeight  # Einfacher XPath beibehalten
    type: float
    fallback: null
  year_of_construction:
    xpath: .//gen:stringAttribute  # Vereinfacht - Logik jetzt in Python
    type: int
    fallback: null
    search_text: "Baujahr"  # Neues Feld für die Python-Suche
  building_type:
    xpath: .//gen:stringAttribute  # Vereinfacht - Logik jetzt in Python
    type: str
    fallback: "unknown"
    search_text: "Nutzung"  # Neues Feld für die Python-Suche
  name:
    xpath: .//gen:stringAttribute
    type: str
    fallback: null
    search_text: "Name"
  house_no:
    xpath: .//gen:stringAttribute
    type: str
    fallback: null
    search_text: "Hausnummer"
  street:
    xpath: .//gen:stringAttribute
    type: str
    fallback: null
    search_text: "Strasse"
  postcode:
    xpath: .//gen:stringAttribute
    type: str
    fallback: null
    search_text: "PLZ"
  city:
    xpath: .//gen:stringAttribute
    type: str
    fallback: "Wien"
    search_text: "Stadt"
  country:
    xpath: .//bldg:address/core:Address/xAL:AddressDetails/xAL:Country/xAL:CountryName
    type: str
    fallback: "Österreich"

# Fallback-XPath für Adressfelder
fallback_address_xpath:
  street: "Building/address/Address/street"
  house_no: "Building/address/Address/houseNumber"
  postcode: "Building/address/Address/postalCode"
  city: "Building/address/Address/city"
  country: "Building/address/Address/country"

building_type_mapping:
  "1000": "AB"
  "2000": "NWG"
  "3000": "OFFICE"
  "4000": "RETAIL"
  "5000": "INDUSTRIAL"
  "6000": "HOSPITAL"
  "7000": "SCHOOL"
  "8000": "HOTEL"

cea_fields:
  Name:
    source: name
    type: str
  Year:
    source: year_of_construction
    type: int
  Use_Type:
    source: building_type
    type: str
  Height_AG:
    source: measured_height
    type: float
  Floors_AG:
    source: measured_height
    type: int
    transform: "max(1, int(x / 3.5))"  # Geschosshöhe ~3.5m
  Street:
    source: street
    type: str
  Streetnumber:
    source: house_no
    type: str
  Postcode:
    source: postcode
    type: str
  City:
    source: city
    type: str 